### ISSUE TITLE
DB integrity error when running basic PR workflow

### ISSUE THREAD

**Issue by zen** [terrateamio/action#237]
Hi,

I'm getting such error:

```
[2024-02-19T11:45:50] [INFO] GITHUB_EVENT : xxxxxxxxx: PULL_REQUEST_EVENT : owner=alphalab-hq : repo=infrastructure : sender=zen
[2024-02-19T11:45:50] [INFO] GITHUB_EVALUATOR : xxxxxxxxx : MAKE : alphalab-hq : infrastructure : pull_number=484 : event_type=autoplan : installation_id=xxxx : tag_query=
[2024-02-19T11:45:50] [ERROR] GITHUB_EVENT : xxxxxxxxx : ERROR : `Integrity_err ({ Pgsql_io.message =
                  "insert or update on table \"github_installation_repositories\" violates foreign key constraint \"github_installation_repositories_installation_id_fkey\"";
                  detail =
                  (Some "Key (installation_id)=(xxxx) is not present in table \"github_installations\".")
                  })
[2024-02-19T11:45:50] [INFO]  : 140.82.115.148 : 1c969433-76a0-4452-b8fb-adaf3fba2547 : POST : 0.461110 : //127.0.0.1:8180/api/github/v1/events : 500 Internal Server Error
```

I also have drift detection configured and having very similar error regularly:

```
[2024-02-19T11:03:43] [ERROR] GITHUB_EVALUATOR : 2af9a696-3002-4581-836b-3777b0d2421b : DRIFT : ERROR : `Integrity_err (
                              { Pgsql_io.message =
                                "insert or update on table \"github_drift_schedules\" violates foreign key constraint \"github_drift_schedules_repository_fkey\"";
                                detail =
                                (Some "Key (repository)=(aaaaaa) is not present in table \"github_installation_repositories\".")
                                })
[2024-02-19T11:03:43] [INFO]  : 140.82.115.173 : 2af9a696-3002-4581-836b-3777b0d2421b : POST : 0.873730 : //127.0.0.1:8180/api/github/v1/events : 200 OK
```

My config is as follows

config.yaml

```
apply_requirements:
  checks:
    approved:
      enabled: false
      count: 1
    merge_conflicts:
      enabled: true
    status_checks:
      enabled: true
      ignore_matching: []
  create_pending_apply_check: true
hooks:
  all:
    pre:
      - type: oidc
        provider: aws
        role_arn: "arn:aws:iam::xxxxxx:role/terrateam"
#default_tf_version: latest
enabled: true
automerge:
  enabled: false
  delete_branch: false
default_tf_version: 1.6.6
dirs:
  terraform/prod-2:
    tags:
      - prod-2
      - production
    when_modified:
      file_patterns: ["**/*.tf", "**/*.tfvars"]
      autoplan: true
      autoplan_draft_pr: true
      autoapply: false
drift:
  enabled: true
  schedule: daily
  reconcile: false
```

Workflow file (.github/workflows/terrateam.yml)

```
name: "Terrateam Workflow"
on:
  workflow_dispatch:
    paths:
      - "terraform/*"
    inputs:
      work-token:
        description: "Work Token"
        required: true
      api-base-url:
        description: "API Base URL"
jobs:
  terrateam:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 1440
    name: Terrateam Action
    steps:
      - uses: actions/checkout@v3
      - name: Run Terrateam Action
        id: terrateam
        uses: terrateamio/action@v1
        with:
          work-token: "${{ github.event.inputs.work-token }}"
          api-base-url: "${{ github.event.inputs.api-base-url }}"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
```

I'm self hosting on kubernetes. Errors in DB are similar: https://pastebin.com/y5Xtp439

App is installed and allowed access to the repository

**Comment by orbitz** [comment]
This looks like you installed your GitHub app on your organization BEFORE running the service.  Try uninstalling then installing again.  You should see a log message showing the installation has been created.

**Comment by zen** [comment]
One more questions then. Docs ask to run `curl -I service` but in my case it responds with 404, not 200. I can see this request reaching service pod in the logs. Is this correct?

I will reinstall the app then and see, although I'm almost 100% sure I installed the GH App after installing Ingress and enabling `github_webhook_url_update: "true"`

**Comment by orbitz** [comment]
@zen If you jump on our Slack I can help you in real time, but at the end we definitely need to see the "INSTALLATION : CREATED" log message.

For the curl, that might be a mistake for the k8s instructions.  For the other instructions there is an nginx config infront of it that handles the HEAD, but the service backend takes `GET`, so try the curl without the `-I` and I'll update documentation or backend to work correctly according to docs.

**Comment by zen** [comment]
Tha k you guys. 

I tried, but when following invitation link I'm stuck on last page. I'm using Google account, tried other browsers. I can accept other invitations though.

Will try with other account later.

**Comment by zen** [comment]
Tha k you guys. 

I tried, but when following invitation link I'm stuck on last page. I'm using Google account, tried other browsers. I can accept other invitations though.

Will try with other account later.

**Comment by zen** [comment]
For future reference: somehow Github App was installed before terrateam service public endpoint was ready, so it couldn't register all the data in DB. Fixed by reinstalling GH App.
